---
title: "iModEst_Fig2c_OnlineData"
author: "Lauren Erdman"
date: "January 11, 2023"
output: html_document
---


```{r, include=FALSE}

##
##  LIBRARIES
##

library("ggplot2")
library("reshape")
library("RColorBrewer")
library("httr")

```

```{r, include=FALSE}
##
## MISC FUNCTIONS FOR THE PLOTTING AND ANALYSIS OF iModEst
##

read_remote_rds <- function(url) {
  # Make a GET request and save the response
  response <- GET(url)
 
  # Check if the request was successful
  stop_for_status(response)
 
  # Write the raw content to a temporary file and read it with readRDS
  temp_file <- tempfile(fileext = ".rds")
  writeBin(content(response), temp_file)
  data <- readRDS(temp_file)
 
  # Return the data
  return(data)
}


add.alpha <- function(col, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
        function(x) 
          rgb(x[1], x[2], x[3], alpha=alpha))  
}

plot.r2.addition <- function(df,row.num,ylim=c(-1,1)){
  vars.removed <- matrix(nrow=0,ncol=3)
  colnames(vars.removed) <- c("var.added","base.model","r2.growth")
  
  for(k in rev(unique(nchar(colnames(df))))[1:(length(rev(unique(nchar(colnames(df)))))-1)]){
    mods <- colnames(df)[which(nchar(colnames(df)) == k)]
    mods.min.1 <- colnames(df)[which(nchar(colnames(df)) == (k-1))]
    
    for(i in 1:6){
      vars.removed <- rbind(vars.removed,cbind(rep(i,length(mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)])),mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)],unlist(df[row.num,mods[grep(pattern = i,x = mods)]] - df[row.num,mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)]])))
    }
  }
  
  # dim(vars.removed)
  # head(vars.removed)
  
  vars.removed <- as.data.frame(vars.removed)
  vars.removed$r2.growth <- as.numeric(as.character(vars.removed$r2.growth))
  vars.removed$var.added.f <- factor(vars.removed$var.added,levels=1:6,labels=c("miRNA","TF","lncRNA","methyl","CNV","SNP"))
  vars.removed$base.model <- as.character(vars.removed$base.model)
  # str(vars.removed)
  # head(vars.removed)
  
  ## DARKER = VARIABLE ADDED TO MODEL WITH FEWER PREDICTORS
  graph.list <- split(x = vars.removed$r2.growth,f = vars.removed$var.added.f)
  # sapply(1:)
  alpha.list <- split(x = 1-nchar(x = vars.removed$base.model)/10,f = vars.removed$var.added.f)
  
  # par(mfrow=c(1,1))
  # stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = add.alpha(col = "darkorchid",alpha = 0.7))
  stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = 'white',ylim=ylim,
             xlab = "",ylab = "",cex=2)
  for(k in 1:6){
    points(x = rep(k,length(graph.list[[k]])) + rnorm(n = length(graph.list[[k]]),0,0.1),y = graph.list[[k]],col = add.alpha(col = "blue",alpha.list[[k]]*2),pch=19,cex=2)
    points(x = k, y = df[row.num,paste0("glm_",k)],pch = 18,col = 'red',cex=2)
  }
  
  
}

plot.r2.addition.ZERO <- function(df,row.num,ylim=c(-1,1)){
  vars.removed <- matrix(nrow=0,ncol=3)
  colnames(vars.removed) <- c("var.added","base.model","r2.growth")
  
  df[df < 0] <- 0
  
  for(k in rev(unique(nchar(colnames(df))))[1:(length(rev(unique(nchar(colnames(df)))))-1)]){
    mods <- colnames(df)[which(nchar(colnames(df)) == k)]
    mods.min.1 <- colnames(df)[which(nchar(colnames(df)) == (k-1))]
    
    for(i in 1:6){
      vars.removed <- rbind(vars.removed,cbind(rep(i,length(mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)])),mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)],unlist(df[row.num,mods[grep(pattern = i,x = mods)]] - df[row.num,mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)]])))
    }
  }
  
  # dim(vars.removed)
  # head(vars.removed)
  
  vars.removed <- as.data.frame(vars.removed)
  vars.removed$r2.growth <- as.numeric(as.character(vars.removed$r2.growth))
  vars.removed$var.added.f <- factor(vars.removed$var.added,levels=1:6,labels=c("miRNA","TF","lncRNA","methyl","CNV","SNP"))
  vars.removed$base.model <- as.character(vars.removed$base.model)
  # str(vars.removed)
  # head(vars.removed)
  
  ## DARKER = VARIABLE ADDED TO MODEL WITH FEWER PREDICTORS
  graph.list <- split(x = vars.removed$r2.growth,f = vars.removed$var.added.f)
  # sapply(1:)
  alpha.list <- split(x = 1-nchar(x = vars.removed$base.model)/10,f = vars.removed$var.added.f)
  
  # par(mfrow=c(1,1))
  # stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = add.alpha(col = "darkorchid",alpha = 0.7))
  stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = 'white',ylim=ylim,
             xlab = "",ylab = "",cex=2)
  for(k in 1:6){
    points(x = rep(k,length(graph.list[[k]])) + rnorm(n = length(graph.list[[k]]),0,0.1),y = graph.list[[k]],col = add.alpha(col = "blue",alpha.list[[k]]*2),pch=19,cex=2)
    points(x = k, y = df[row.num,paste0("glm_",k)],pch = 18,col = 'red',cex=2)
  }
  
  
}

get.r2.addition.ZERO <- function(df,row.num,ylim=c(-1,1)){
  vars.removed <- matrix(nrow=0,ncol=4)
  colnames(vars.removed) <- c("var.added","base.model","r2.growth","mod.r2")
  
  df[df < 0] <- 0
  
  for(k in rev(unique(nchar(colnames(df))))[1:(length(rev(unique(nchar(colnames(df)))))-1)]){
    mods <- colnames(df)[which(nchar(colnames(df)) == k)]
    mods.min.1 <- colnames(df)[which(nchar(colnames(df)) == (k-1))]
    
    for(i in 1:6){
      vars.removed <- rbind(vars.removed,
                            cbind(rep(i,length(mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)])),
                                  mods.min.1[grep(pattern = i,x = mods.min.1,invert = TRUE)],
                                  unlist(df[row.num,mods[grep(pattern = i,x = mods)]] - 
                                           df[row.num,mods.min.1[grep(pattern = i,x = mods.min.1, invert = TRUE)]]),
                                  unlist(df[row.num,mods[grep(pattern = i,x = mods)]] - 
                                           rep(0,length(df[row.num,mods.min.1[grep(pattern = i,x = mods.min.1, invert = TRUE)]])))))
    }
  }
  
  # dim(vars.removed)
  # head(vars.removed)
  
  vars.removed <- as.data.frame(vars.removed)
  vars.removed$r2.growth <- as.numeric(as.character(vars.removed$r2.growth))
  vars.removed$mod.r2 <- as.numeric(as.character(vars.removed$mod.r2))
  vars.removed$var.added.f <- factor(vars.removed$var.added,levels=1:6,labels=c("miRNA","TF","lncRNA","methyl","CNV","SNP"))
  vars.removed$base.model <- as.character(vars.removed$base.model)
  vars.removed$gene <- rownames(df)[row.num]
  # str(vars.removed)
  # head(vars.removed)
  
  return(vars.removed) 
  
  ## DARKER = VARIABLE ADDED TO MODEL WITH FEWER PREDICTORS
  # graph.list <- split(x = vars.removed$r2.growth,f = vars.removed$var.added.f)
  # alpha.list <- split(x = 1-nchar(x = vars.removed$base.model)/10,f = vars.removed$var.added.f)
  
  # par(mfrow=c(1,1))
  # stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = add.alpha(col = "darkorchid",alpha = 0.7))
  
  ## STRIPCHART
  # stripchart(split(x = vars.removed$r2.growth,f = vars.removed$var.added.f),method = "jitter",vertical = T,pch=19,col = 'white',ylim=ylim,
  #            xlab = "",ylab = "",cex=2)
  # for(k in 1:6){
  #   points(x = rep(k,length(graph.list[[k]])) + rnorm(n = length(graph.list[[k]]),0,0.1),y = graph.list[[k]],col = add.alpha(col = "blue",alpha.list[[k]]*2),pch=19,cex=2)
  #   points(x = k, y = df[row.num,paste0("glm_",k)],pch = 18,col = 'red',cex=2)
  # }
  
  
}

gg_color_hue <- function(n) {
  ## ggplot default rainbow colors from: https://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette 
  # hues = seq(15, 375, length = n + 1)
  hues = seq(25, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


```

##Set fixed values for script
```{r}

##
##  SET FIXED COLORS FOR EACH TUMOUR 
##

n <- 21
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
col_vector = col_vector[seq(1,length(col_vector),round(length(col_vector)/22))]
# col_vector = palette(rainbow(21)) 


# pie(rep(1,n), col=gg_color_hue(21))

tum.cols <- gg_color_hue(21)

reg.cols <- brewer.pal(n = 6,name = "Dark2")

cans <- "BLCA, BRCA, CESC, ESCA, HNSC, KIRC, KIRP, LGG, LIHC, LUAD, LUSC, PAAD, PCPG, PRAD, READ-COAD, SARC, SKCM, STAD, TGCT, THCA, UCEC"
tums <- unlist(strsplit(x = cans,split = ",\ "))
# length(tums)
names(tum.cols) <- tums
tum.vec <- tums
cancers.of.int <- tums

cancers.of.int_normal <- c("BLCA","BRCA","ESCA","HNSC","KIRC","KIRP","LIHC","LUAD","LUSC","PAAD","PCPG","PRAD","THCA","UCEC")

norm.vec <- cancers.of.int_normal
```

##Reading in variance explained data
```{r}
#####
###   READING IN TUMOUR FILES -- R2
#####

# tumour.file.list <- list.files(path = 'C:/Users/larun/Desktop/Modes/Data//tumour pred model performance/r2')
# # tumour.file.list <- tumour.file.list[unlist(sapply(tum.vec, function(cancer){grep(pattern = cancer,x = tumour.file.list)}))]
# tumour.file.list <- tumour.file.list[na.omit(unlist(sapply(tums,function(tum){grep(tum,tumour.file.list)})))]
# tumour.file.list <- tumour.file.list[grep("_tumor_r_square_1.rds",tumour.file.list)]

tumour.r2.dfs <- list()
gene.tum.details.df <- list()
# clinic.list <- list()

k=1
for(cancer in cancers.of.int){
  
  ## Reading in PRESS R2 results
  tumour.r2.dfs[[k]] <- read_remote_rds(paste0('https://imodesttool.com/api/data/download/full/performance_files/tumour_PRESS_R2/',cancer,"_0_tumor_r_square_1.rds")) 
  # cancer <- gsub(pattern = "_.*$",replacement = "",x = tumour.file.in)
  names(tumour.r2.dfs)[k] <- cancer
  
  
  ## Reading in cancer model details
  summary_file = paste0(cancer,"_0_data_summary.rds")
  
  
  ## Reading in cancer model details
  gene.tum.details.df[[k]] <- read_remote_rds(paste0('https://imodesttool.com/api/data/download/full/performance_files/summary_files/',summary_file))
  names(gene.tum.details.df)[k] <- cancer
  
  # clinic.list[[k]] <-  readRDS(paste0('C:/Users/larun/Desktop/Modes/Data/clinical-model-input/',list.files('C:/Users/larun/Desktop/Modes/Data/clinical-model-input/')[grep(pattern = cancer,x = list.files('C:/Users/larun/Desktop/Modes/Data/clinical-model-input//'))]))
  # names(clinic.list)[k] <- cancer
  
  k=k+1
}

# save(list = c("tumour.dfs"),file = "C:/Users/larun/Desktop/Modes/App/App prototype/Data/corr-tumour.dfs.RData")

# length(tumour.r2.dfs)
# names(tumour.r2.dfs)

# 
tum.r2.dfs  <- tumour.r2.dfs#[tum.vec]
tum.r2.dfs.sub  <- tumour.r2.dfs#[tum.vec]

# names(gene.tum.details.df)
# length(gene.tum.details.df)

### MAKING OVERALL GENE SUMMARY
num.reg.sum <- lapply(gene.tum.details.df,function(x){x$NUM_REGULATORS})
tum.overall.summary <- Reduce(rbind,num.reg.sum)
tum.overall.summary <- tum.overall.summary[!duplicated(tum.overall.summary$target_id),]


#####
###   READING IN NORMAL FILES -- R2
#####

# (norm.file.list <- list.files(path = 'C:/Users/larun/Desktop/Modes/Data/normal pred model performance/r2/'))
# (norm.file.list <- norm.file.list[unlist(sapply(norm.vec, function(cancer){grep(pattern = cancer,x = norm.file.list)}))])

norm.r2.dfs <- list()
gene.norm.details.df <- list()

k=1
for(cancer in cancers.of.int_normal){
  
  norm.file.in = paste0(cancer,"_0_",cancer,"_0_r_square_1.rds")
  
  ## Reading in PRESS R2 results
  norm.r2.dfs[[k]] <- read_remote_rds(paste0('https://imodesttool.com/api/data/download/full/performance_files/tumour-adjacent_tissue_PRESS_R2/',norm.file.in)) 
  # cancer <- gsub(pattern = "_.*$",replacement = "",x = norm.file.in)
  names(norm.r2.dfs)[k] <- cancer
  
  ## Reading in cancer model details
  summary_file = paste0(cancer,"_0_data_summary.rds")
  
  
  ## Reading in cancer model details
  gene.tum.details.df[[k]] <- read_remote_rds(paste0('https://imodesttool.com/api/data/download/full/performance_files/summary_files/',summary_file))
  names(gene.tum.details.df)[k] <- cancer
  
  # clinic.list[[k]] <-  readRDS(paste0('C:/Users/larun/Desktop/Modes/Data/clinical-model-input/',list.files('C:/Users/larun/Desktop/Modes/Data/clinical-model-input/')[grep(pattern = cancer,x = list.files('C:/Users/larun/Desktop/Modes/Data/clinical-model-input//'))]))
  # names(clinic.list)[k] <- cancer
  
  k=k+1
}

# save(list = c("tumour.dfs"),file = "C:/Users/larun/Desktop/Modes/App/App prototype/Data/corr-tumour.dfs.RData")

# length(norm.r2.dfs)
# names(norm.r2.dfs)
# str(norm.r2.dfs)

# 
# tum.r2.dfs.sub  <- tumour.r2.dfs#[tum.vec]

# names(gene.norm.details.df)

# str(tumour.dfs)
# tumour.dfs[["UCEC"]][1:10,1:10]
# head(rownames(tumour.dfs[["UCEC"]]))

### MAKING OVERALL GENE SUMMARY
num.reg.sum <- lapply(gene.norm.details.df,function(x){x$NUM_REGULATORS})
norm.overall.summary <- Reduce(rbind,num.reg.sum)
norm.overall.summary <- norm.overall.summary[!duplicated(norm.overall.summary$target_id),]
# str(norm.overall.summary)

```


## Reading in variance added data
```{r}

  ###
  ###   TUM VAR ADDED DATA
  ### 

## reading in top regulators

tum.r2.added.list <- list()

for(cancer in tum.vec){
  tum.r2.added.list[[cancer]] <- read_remote_rds(paste0("https://imodesttool.com/api/data/download/full/performance_files/subset_tumour_var_added_files/",cancer,"-var-added-list.rds"))
}


###
###     GETTING MEAN PRESS R2 OVER OVERLAPPING GENES IN 21 CANCERS
###

get.mean.add.r2.by.reg <- function(r2.added.can.list){
  means.by.reg.list <- lapply(r2.added.can.list,function(x){
    sapply(1:6,function(i){
      mean(x$r2.growth[x$var.added == as.character(i)])
    })
  })
  return(means.by.reg.list)
}

tum.r2.added.means.list <- lapply(tum.r2.added.list,get.mean.add.r2.by.reg)
# str(r2.added.means.list)

## mean over all cancers
apply(data.frame(tum.r2.added.means.list),1,mean)
apply(data.frame(tum.r2.added.means.list),1,median)
apply(data.frame(tum.r2.added.means.list),1,range)


        ###
        ###     NORMAL VAR ADDED DATA
        ### 

norm.r2.added.list <- list()

## need these added by Arnav
for(cancer in cancers.of.int_normal){
  norm.r2.added.list[[cancer]] <- read_remote_rds(paste0("https://imodesttool.com/api/data/download/full/performance_files/tumour-adjacent_R2_added_files/",cancer,"-var-added-list.rds"))
}

norm.r2.added.means.list <- lapply(norm.r2.added.list,get.mean.add.r2.by.reg)
# str(r2.added.means.list)

norm.reg.means.df.by.can <- lapply(norm.r2.added.means.list,function(x){
  bound.fields <- data.frame(Reduce(rbind,x))
  names(bound.fields) <- c("miRNA","TF","lncRNA","methyl","CNV","SNP")
  return(bound.fields)
})

for(i in 1:length(norm.reg.means.df.by.can)){
  rownames(norm.reg.means.df.by.can[[i]]) <- names(norm.r2.added.list[[1]])
}


## mean over all cancers
# apply(data.frame(norm.r2.added.means.list),1,mean)
# apply(data.frame(norm.r2.added.means.list),1,median)
# apply(data.frame(norm.r2.added.means.list),1,range)
# 
# merged.r2added = merge(t(data.frame(tum.r2.added.means.list$BLCA)),t(data.frame(norm.r2.added.means.list$BLCA)),by="row.names")
# head(merged.r2added)
# 
# cor.test(merged.r2added$V1.x,merged.r2added$V1.y)
# cor.test(merged.r2added$V2.x,merged.r2added$V2.y)
# cor.test(merged.r2added$V3.x,merged.r2added$V3.y)
# cor.test(merged.r2added$V4.x,merged.r2added$V4.y)
# cor.test(merged.r2added$V5.x,merged.r2added$V5.y)
# cor.test(merged.r2added$V6.x,merged.r2added$V6.y)

cor_df = data.frame(matrix(nrow = 6*length(names(norm.r2.added.means.list)),ncol=5))
names(cor_df) = c("cancer","regualtor","cor","lcl","ucl")
cor_df$cancer = rep(names(norm.r2.added.means.list),each = 6)
cor_df$regualtor =rep(c("miRNA","TF","lncRNA","methyl","CNV","SNP"),times = length(names(norm.r2.added.means.list)))

for(cancer in cancers.of.int){
  if(cancer %in% names(norm.r2.added.means.list)){
    merged.r2added = merge(t(data.frame(tum.r2.added.means.list[[cancer]])),t(data.frame(norm.r2.added.means.list[[cancer]])),by="row.names")

    mirna.cor = cor.test(merged.r2added$V1.x,merged.r2added$V1.y)
    tf.cor = cor.test(merged.r2added$V2.x,merged.r2added$V2.y)
    lncrna.cor = cor.test(merged.r2added$V3.x,merged.r2added$V3.y)
    methyl.cor = cor.test(merged.r2added$V4.x,merged.r2added$V4.y)
    cnv.cor = cor.test(merged.r2added$V5.x,merged.r2added$V5.y)
    snp.cor = cor.test(merged.r2added$V6.x,merged.r2added$V6.y)
    
    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "miRNA"] = mirna.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "miRNA"] = mirna.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "miRNA"] = mirna.cor$conf.int[2]
    
    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "TF"] = tf.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "TF"] = tf.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "TF"] = tf.cor$conf.int[2]

    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "lncRNA"] = lncrna.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "lncRNA"] = lncrna.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "lncRNA"] = lncrna.cor$conf.int[2]

    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "methyl"] = methyl.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "methyl"] = methyl.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "methyl"] = methyl.cor$conf.int[2]

    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "CNV"] = cnv.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "CNV"] = cnv.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "CNV"] = cnv.cor$conf.int[2]

    cor_df$cor[cor_df$cancer == cancer & cor_df$regualtor == "SNP"] = snp.cor$estimate
    cor_df$lcl[cor_df$cancer == cancer & cor_df$regualtor == "SNP"] = snp.cor$conf.int[1]
    cor_df$ucl[cor_df$cancer == cancer & cor_df$regualtor == "SNP"] = snp.cor$conf.int[2]
  }
}

# head(cor_df)

cor_df$regualtor = factor(cor_df$regualtor,levels = c("miRNA","TF","lncRNA","methyl","CNV","SNP"))

cor_df = cor_df[cor_df$cancer != "HNSC",]
# ggplot(cor_df,aes(y = cor, x = regualtor,col = cancer)) + 
#   geom_point() + geom_errorbar(aes(ymin = lcl, ymax = ucl)) + 
#   ylim(c(-1,1))
# 

```

##Create correlation plot 
```{r}
ggplot(cor_df,aes(y = cor, x = regualtor)) + 
  geom_bar(position=position_dodge(), stat="identity",aes(fill=cancer)) +
  geom_errorbar(aes(ymin=lcl, ymax=ucl, col = cancer),
                width=.2,                    # Width of the error bars
                position=position_dodge(.9)) + 
  ylim(c(-1,1)) + 
  scale_fill_manual(values = tum.cols[names(tum.cols) %in% cor_df$cancer]) + 
  scale_colour_manual(values = tum.cols[names(tum.cols) %in% cor_df$cancer]) + 
  theme_classic()
```

